### ISSUE TITLE
KubeJS error recipe

### ISSUE THREAD

**Issue by Proxwian** [Therighthon/ArborFirmaCraft#6]
`[13:08:14] [ERROR] ! Error in 'ServerEvents.recipes': null
[13:08:14] [ERROR] ! java.lang.NullPointerException
[13:08:14] [ERROR] !   at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:08:14] [ERROR] !   at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:08:14] [ERROR] !   at …kubejs.recipe.RecipesEventJS.runInParallel(RecipesEventJS.java:715)
[13:08:14] [ERROR] !   at …kubejs.recipe.RecipesEventJS.forEachRecipeAsync(RecipesEventJS.java:545)
[13:08:14] [ERROR] !   at …kubejs.recipe.RecipesEventJS.remove(RecipesEventJS.java:580)
[13:08:14] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[13:08:14] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[13:08:14] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[13:08:14] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[13:08:14] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[13:08:14] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[13:08:14] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[13:08:14] [ERROR] !   at …rhino.Context.doTopCall(Context.java:1307)
[13:08:14] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[13:08:14] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[13:08:14] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[13:08:14] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[13:08:14] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[13:08:14] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[13:08:14] [ERROR] !   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy111.onEvent(Unknown Source)
[13:08:14] [ERROR] !   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[13:08:14] [ERROR] !   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[13:08:14] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:272)
[13:08:14] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[13:08:14] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:189)
[13:08:14] [ERROR] !   at …kubejs.recipe.RecipesEventJS.post(RecipesEventJS.java:356)
[13:08:14] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.handler$zzi000$customRecipesHead(RecipeManager.java:6031)
[13:08:14] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java)
[13:08:14] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34)
[13:08:14] [ERROR] !   at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
[13:08:14] [ERROR] !   at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[13:08:14] [ERROR] !   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:08:14] [ERROR] !   at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
[13:08:14] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[13:08:14] [ERROR] !   at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[13:08:14] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[13:08:14] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[13:08:14] [ERROR] !   at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:4941)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_246486_(WorldOpenFlows.java:163)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:113)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:181)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:169)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:65)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:575)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:474)
[13:08:14] [ERROR] !   at java.util.Optional.ifPresent(Optional.java:178)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_232979_(SelectWorldScreen.java:59)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.components.Button.m_5691_(Button.java:38)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:55)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:175)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38)
[13:08:14] [ERROR] !   at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92)
[13:08:14] [ERROR] !   at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437)
[13:08:14] [ERROR] !   at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89)
[13:08:14] [ERROR] !   at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189)
[13:08:14] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102)
[13:08:14] [ERROR] !   at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
[13:08:14] [ERROR] !   at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
[13:08:14] [ERROR] !   at com.mojang.blaze3d.systems.RenderSystem.handler$baa000$handleWaitEventsTimeout(RenderSystem.java:1508)
[13:08:14] [ERROR] !   at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
[13:08:14] [ERROR] !   at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1173)
[13:08:14] [ERROR] !   at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
[13:08:14] [ERROR] !   at net.minecraft.client.main.Main.main(Main.java:218)
[13:08:14] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[13:08:14] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[13:08:14] [ERROR] !   at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[13:08:14] [ERROR] ! Caused by: java.lang.NullPointerException: ItemStack should never be null, but recipe afc:tree_tapping/birch_syrup[afc:tree_tapping] returned null as the output!
[13:08:14] [ERROR] !   at …kubejs.recipe.JsonRecipeJS.hasOutput(JsonRecipeJS.java:41)
[13:08:14] [ERROR] !   at …kubejs.recipe.filter.OutputFilter.test(OutputFilter.java:15)
[13:08:14] [ERROR] !   at …kubejs.recipe.filter.OrFilter.test(OrFilter.java:14)
[13:08:14] [ERROR] !   at …kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:494)
[13:08:14] [ERROR] !   at …kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:491)
[13:08:14] [ERROR] !   at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[13:08:14] [ERROR] !   at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
[13:08:14] [ERROR] !   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[13:08:14] [ERROR] !   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[13:08:14] [ERROR] !   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[13:08:14] [ERROR] !   at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[13:08:14] [ERROR] !   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[13:08:14] [ERROR] !   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[13:08:14] [ERROR] !   at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[13:08:14] [ERROR] !   at …kubejs.recipe.RecipesEventJS.lambda$forEachRecipeAsync$11(RecipesEventJS.java:545)
[13:08:14] [INFO] Posted recipe events in 34.80 ms
`

Because of this error, KubeJS can't load my custom recipes from folder

**Comment by ChiefArug** [comment]
A slightly more readable version of the log: https://gnomebot.dev/paste/1202521086433038356#L96

This is a very strange error, as in the code its hardcoded to always return ItemStack.EMPTY and that file hasn't been touched in 7 months: [TreeTapRecipe.java#L108-L112](https://github.com/Therighthon/ArborFirmaCraft/blob/e74f07de259983f94379ae218c54fd01f5838b3f/src/main/java/com/therighthon/afc/common/recipe/TreeTapRecipe.java#L108-L112)

**Comment by ChiefArug** [comment]
Scratch that, turns out the main branch isnt the latest version of minecraft. The actual code is here: [TreeTapRecipe.java#L108-L112](https://github.com/Therighthon/ArborFirmaCraft/blob/1.20/src/main/java/com/therighthon/afc/common/recipe/TreeTapRecipe.java#L108-L112) and it is returning null, which should be replaced with ItemStack.EMPTY

**Comment by ChiefArug** [comment]
Fixed by https://github.com/Therighthon/ArborFirmaCraft/commit/092c78f5ddd4b2462e28cf329d53bccd2c21088e

**Comment by Therighthon** [comment]
Thanks for the report!
